
```{r, eval = FALSE}
install.packages("ape")
```

```{r, eval = FALSE}
library(ape)
```

```{r}
primatedata <- read.table("Primatedata.txt", sep = "\t", header = TRUE)
```

```{r}
str(primatedata)
```

```{r}
head(primatedata)
```

```{r}
names(primatedata)
```
This gives you the names of the columns.

```{r, eval = FALSE}
primatedata
```

```{r}
primatetree <- read.nexus("consensusTree_10kTrees_Version2.nex") 
```

Let’s examine the tree by typing:

```{r}
primatetree
str(primatetree)
```

```{r , eval = FALSE}
plot(primatetree)
```

```{r, eval = FALSE}
plot(primatetree, cex = 0.5)
```

```{r, eval = FALSE}
zoom(primatetree, list(grep("Cercopithecus", primatetree$tip.label)), 
     subtree = FALSE)
```

```{r, eval = FALSE}
zoom(primatetree, list(grep("Cercopithecus", primatetree$tip.label)), 
     subtree = TRUE)
```

```{r}
primatetree2 <-drop.tip(primatetree, "Aotus_azarae_infulatus")
str(primatetree2)
```

```{r, eval = FALSE}
?plot.phylo
```

```{r, eval = FALSE}
par(mfrow = c(1,1)) 
plot(primatetree, type = "fan", edge.color = "deeppink", 
     tip.color = "green", cex = 0.5)
```

```{r, eval = FALSE}
plot(primatetree)
axisPhylo()
```

```{r}
is.binary.tree(primatetree) # we want this to be TRUE
primatetree <- multi2di(primatetree) 
```

```{r, eval = FALSE}
primatetree.reroot <- root(primatetree, "Saimiri_sciureus")
plot(primatetree.reroot)
```
```{r}
primatedata$Binomial <- gsub(" ", "_", primatedata$Binomial)
```

```{r}
row.names(primatedata) <- primatedata$Binomial
```

```{r}
primatedata2 <- primatedata[, 4:8]
```

```{r}
match.species <- treedata(primatetree, primatedata2)
```

```{r}
mytree <- match.species$phy
mydata <- match.species$data
```

```{r}
BM <- fitContinuous(mytree, log(mydata[,"AdultBodyMass_g"]), model = c("BM"))
```

```{r}
BM
```

```{r}
OU <- fitContinuous(mytree, log(mydata[,"AdultBodyMass_g"]), model = c("OU"))
```

```{r}
OU
```

```{r}
EB <- fitContinuous(mytree, log(mydata[,"AdultBodyMass_g"]), model = c("EB"))
```

```{r}
EB
```