\documentclass[12pt]{article}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
    \usepackage{xltxtra,xunicode}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
  \newcommand{\euro}{€}
\fi
% use microtype if available
\IfFileExists{microtype.sty}{\usepackage{microtype}}{}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{{#1}}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{{#1}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{{#1}}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\RegionMarkerTok}[1]{{#1}}
\newcommand{\ErrorTok}[1]{\textbf{{#1}}}
\newcommand{\NormalTok}[1]{{#1}}
\usepackage{graphicx}
% Redefine \includegraphics so that, unless explicit options are
% given, the image width will not exceed the width of the page.
% Images get their normal width if they fit onto the page, but
% are scaled down if they would overflow the margins.
\makeatletter
\def\ScaleIfNeeded{%
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother
\let\Oldincludegraphics\includegraphics
{%
 \catcode`\@=11\relax%
 \gdef\includegraphics{\@ifnextchar[{\Oldincludegraphics}{\Oldincludegraphics[width=\ScaleIfNeeded]}}%
}%
\ifxetex
  \usepackage[setpagesize=false, % page size defined by xetex
              unicode=false, % unicode breaks when used with xetex
              xetex]{hyperref}
\else
  \usepackage[unicode=true]{hyperref}
\fi
\hypersetup{breaklinks=true,
            bookmarks=true,
            pdfauthor={},
            pdftitle={},
            colorlinks=true,
            citecolor=blue,
            urlcolor=blue,
            linkcolor=magenta,
            pdfborder={0 0 0}}
\urlstyle{same}  % don't use monospace font for urls
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\setcounter{secnumdepth}{0}
\usepackage{fullpage}
\usepackage{framed}

\begin{document}

\title{Phylogenetic Comparative Methods in R\\
Using phylogeny as a statistical fix}
\author{Natalie Cooper (ncooper@tcd.ie)}
\date{}
\maketitle

The aims of this problem set are to learn how to use R to answer phylogenetic 
comparative questions without panicking! By the end of this problem set you 
should be able to:

\begin{enumerate}
\item Read in your data and phylogeny
\item Match taxa in your phylogeny with those in your dataset
\item View and manipulate your phylogeny
\item Calculate measures of phylogenetic signal (lambda and K)
\item Perform PGLS analyses using caper
\item Perform a phylogenetic ANOVA using geiger
\end{enumerate}

We will be using the evolution of primate life-history variables as an
example. These data come from the PanTHERIA database (Jones \textit{et
al}. 2009) and 10kTrees (Arnold \textit{et al}. 2010). Note that this is
an old version of 10kTrees, so if you want to use it in your research
please download the newest version.

\begin{framed}
Note that many things in R can be done in multiple ways. You should
choose the methods you feel most comfortable with, and do not panic if
someone is doing the same analyses as you in a different way! This
workshop will be full of different ways to do things.
\end{framed}

\newpage{}
\section{Preparations}

\subsection{Downloading the data and finding the path of your folder}

First you need to download all the files for this problem set into a
folder somewhere on your computer, let's call it ``RAnalyses2014'' and
pop it on the Desktop. We will use this folder throughout the problem
set. You'll need to know what the \textbf{path} of the folder is. For
example on my Windows machine, the path is:

\begin{snugshade}
\texttt{C:/Users/Natalie/Desktop/RAnalyses2014}
\end{snugshade}

The path is really easy to find in a Windows machine, just click on the
address bar of the folder and the whole path will appear.

\begin{framed}
In Windows, paths usually include \textbackslash{} but R
can't read these. It's easy to fix in your R code, just change any \textbackslash{} in
the path to / or \textbackslash{}\textbackslash{}.
\end{framed}

On my Mac the path is:

\begin{snugshade}
\texttt{\textasciitilde{}/Desktop/RAnalyses2014}
\end{snugshade}

It's a bit trickier to find the path on a Mac, and note that the tilde
\textasciitilde{} is a shorthand for /Users/Natalie.

\subsection{Using a text editor}

Next, open a text editor. R has an inbuilt editor that works pretty
well, but NotePad and TextEdit are fine too. However, in the future I
\textbf{highly} recommend using something that will highlight code for
you. My personal favorite is Sublime Text 2, because you can also use
it for any other kind of text editing like LaTeX, html etc.

You should type (or copy and paste) your code into the text editor, edit
it until you think it'll work, and then paste it into R's console
window. Saving the text file lets you keep a record of the code you
used, which can be a great timesaver if you want to use it again,
especially as you know this code will work!

In this problem set, you'll largely be cutting and pasting. This handout
contains pretty much all the R code you need. However, it also sometimes
includes the prompts (\textgreater{}) and continuation signs (+). You
don't want to paste these into R, so edit them out in your text editor.
If you want to add comments to the file (i.e., notes to remind yourself
what the code is doing), put a hash/pound sign (\#) in front of the
comment.

\begin{snugshade}
\texttt{\# Comments are ignored by R but can remind you what the code is doing.\\}
\texttt{\# You need a hash sign at the start of each line of a comment.}
\end{snugshade}

\subsection{Installing extra packages in R}\label{installing-packages}

To run comparative analyses (or any specialised analysis) in R, you need to 
download one or more additional packages from the basic R installation. 
For this problems set you will need to install the following packages: 
\texttt{ape}, \texttt{geiger}, \texttt{picante} and \texttt{caper}. 
To install the package \texttt{ape}:

\begin{snugshade}
\begin{Highlighting}[]
\KeywordTok{install.packages}\NormalTok{(}\StringTok{"ape"}\NormalTok{)}
\end{Highlighting}
\end{snugshade}

Now install \texttt{geiger}, \texttt{picante} and \texttt{caper}.

\subsection{Loading packages in R}

You've installed the packages but they don't automatically get loaded
into your R session. Instead you need to tell R to load them \textbf{every
time} you start a new R session and want to use functions from these
packages. To load the package ape into your current R session:

\begin{snugshade}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ape)}
\end{Highlighting}
\end{snugshade}

Don't forget to load \texttt{geiger}, \texttt{picante} and \texttt{caper} too!

\subsection{Loading data into R}

Next we need to load the data we are going to use for the analysis. R
can read files in lots of formats, including comma-delimited and
tab-delimited files. Excel (and many other applications) can output
files in this format (it's an option in the ``Save As'' dialog box
under the ``File'' menu). To save time I have given you a tab-delimited
text file called ``Primatedata.txt'' which we are going to use. Load
these data as follows:

\begin{snugshade}
\begin{Highlighting}[]
\NormalTok{primatedata <-}\StringTok{ }\KeywordTok{read.table}\NormalTok{(}\StringTok{"Primatedata.txt"}\NormalTok{, }\DataTypeTok{sep =} \StringTok{"}\CharTok{\textbackslash{}t}\StringTok{"}\NormalTok{, }\DataTypeTok{header =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{snugshade}

Note that \texttt{sep = "\textbackslash{}t"} indicates that you have a tab-delimited file, 
\texttt{sep = ","}  would indicate a comma-delimited csv file. You can also use
\texttt{read.delim} for tab delimited files or \texttt{read.csv} for comma delimited
files. \texttt{header = TRUE}, indicates that the first line of the data contains
column headings.

This is a good point to note that unless you \textbf{tell} R you want to
do something, it won't do it automatically. So here if you successfully
entered the data, R won't give you any indication that it worked.
Instead you need to specifically ask R to look at the data.

We can look at the data by typing:

\begin{snugshade}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(primatedata)}
\end{Highlighting}
\end{snugshade}

\begin{verbatim}
## 'data.frame':    77 obs. of  8 variables:
##  $ Order          : Factor w/ 1 level "Primates": 1 1 1 ...
##  $ Family         : Factor w/ 15 levels "Aotidae","Atelidae",...
##  $ Binomial       : Factor w/ 77 levels "Alouatta palliata",...
##  $ AdultBodyMass_g: num  6692 7582 8697 958 558 ...
##  $ GestationLen_d : num  138 226 228 164 154 ...
##  $ HomeRange_km2  : num  2.28 0.73 1.36 0.02 0.32 0.02 ...
##  $ MaxLongevity_m : num  336 328 454 304 215 ...
##  $ SocialGroupSize: num  14.5 42 20 2.95 6.85 ...
\end{verbatim}

This shows the structure of the data frame (this can be a really useful
command when you have a big data file). It also tells you what kind of
variables R thinks you have (characters, integers, numeric, factors
etc.). Some R functions need the data to be certain kinds of variables
so it's useful to check this.

As you can see, the data contains the following variables: Order,
Family, Binomial, AdultBodyMass\_g, GestationLen\_d, HomeRange\_km2,
MaxLongevity\_m, and SocialGroupSize.

\begin{snugshade}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(primatedata)}
\end{Highlighting}
\end{snugshade}

\begin{verbatim}
##      Order      Family           Binomial AdultBodyMass_g GestationLen_d
## 1 Primates    Atelidae   Ateles belzebuth          6692.4          138.2
## 2 Primates    Atelidae   Ateles geoffroyi          7582.4          226.4
## 3 Primates    Atelidae    Ateles paniscus          8697.2          228.2
## 4 Primates Pitheciidae  Callicebus moloch           958.1          164.0
## 5 Primates     Cebidae  Callimico goeldii           558.0          154.0
## 6 Primates     Cebidae Callithrix jacchus           290.2          144.0
##   HomeRange_km2 MaxLongevity_m SocialGroupSize
## 1          2.28          336.0           14.50
## 2          0.73          327.6           42.00
## 3          1.36          453.6           20.00
## 4          0.02          303.6            2.95
## 5          0.32          214.8            6.85
## 6          0.02          201.6            8.55
\end{verbatim}

This gives you the first few rows of data along with the column
headings.

\begin{snugshade}
\begin{Highlighting}[]
\KeywordTok{names}\NormalTok{(primatedata)}
\end{Highlighting}
\end{snugshade}

\begin{verbatim}
## [1] "Order"           "Family"          "Binomial"        "AdultBodyMass_g"
## [5] "GestationLen_d"  "HomeRange_km2"   "MaxLongevity_m"  "SocialGroupSize"
\end{verbatim}

This gives you the names of the columns.

\begin{snugshade}
\begin{Highlighting}[]
\NormalTok{primatedata -}\StringTok{ }\NormalTok{don}\StringTok{'t run}
\end{Highlighting}
\end{snugshade}

This will print out the whole of the dataset!

\subsection{Loading and displaying a phylogeny}

To load a tree you need either the function \texttt{read.tree} or \texttt{read.nexus}.
\texttt{read.tree} can deal with a number of different types of data (including
DNA) whereas \texttt{read.nexus} reads NEXUS files. We will use a NEXUS file of
the consensus tree from 10kTrees.

\begin{snugshade}
\begin{Highlighting}[]
\NormalTok{primatetree <-}\StringTok{ }\KeywordTok{read.nexus}\NormalTok{(}\StringTok{"consensusTree_10kTrees_Version2.nex"}\NormalTok{)}
\end{Highlighting}
\end{snugshade}

Let's examine the tree by typing:

\begin{snugshade}
\begin{Highlighting}[]
\NormalTok{primatetree}
\end{Highlighting}
\end{snugshade}

\begin{verbatim}
## Phylogenetic tree with 226 tips and 221 internal nodes.
## 
## Tip labels:
##  Allenopithecus_nigroviridis, Cercopithecus_ascanius, 
Cercopithecus_cephus, Cercopithecus_cephus_cephus, ...
## 
## Rooted; includes branch lengths.
\end{verbatim}

\begin{snugshade}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(primatetree)}
\end{Highlighting}
\end{snugshade}

\begin{verbatim}
## List of 4
##  $ edge       : int [1:446, 1:2] 227 228 229 230 231 232 ...
##  $ edge.length: num [1:446] 4.95 17.69 19.65 8.12 4.82 ...
##  $ Nnode      : int 221
##  $ tip.label  : chr [1:226] "Allenopithecus_nigroviridis" ...
##  - attr(*, "class")= chr "phylo"
##  - attr(*, "order")= chr "cladewise"
\end{verbatim}

\texttt{primatetree} is a fully resolved tree with branch lengths. There are 226
species and 221 internal nodes. We can plot the tree by using the \texttt{plot}
function of \texttt{ape}:




\end{document}