<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Methods in Macroecology and Macroevolution</title>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta name="description" content="Practical notes for macro module">
  <meta name="generator" content="bookdown 0.3 and GitBook 2.6.7">

  <meta property="og:title" content="Methods in Macroecology and Macroevolution" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Practical notes for macro module" />
  <meta name="github-repo" content="nhcooper123/TeachingMaterials/MSc_Museum/MacroModule" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Methods in Macroecology and Macroevolution" />
  
  <meta name="twitter:description" content="Practical notes for macro module" />
  

<meta name="author" content="Natalie Cooper (natalie.cooper@nhm.ac.uk)">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="phylogenetic-generalised-least-squares-pgls-in-r.html">
<link rel="next" href="macroevolutionary-models-in-r-part-2-discrete-traits.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>


  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Macro Methods Module</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Methods in Macroecology and Macroevolution</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#module-aims"><i class="fa fa-check"></i><b>1.1</b> Module Aims</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#datasets-and-practical-handouts"><i class="fa fa-check"></i><b>1.2</b> Datasets and practical handouts</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#how-to-use-these-materials"><i class="fa fa-check"></i><b>1.3</b> How to use these materials</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#module-outline"><i class="fa fa-check"></i><b>1.4</b> Module outline</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="what-you-need-to-be-able-to-do-in-r-before-you-start.html"><a href="what-you-need-to-be-able-to-do-in-r-before-you-start.html"><i class="fa fa-check"></i><b>2</b> What you need to be able to do in R before you start</a><ul>
<li class="chapter" data-level="2.1" data-path="what-you-need-to-be-able-to-do-in-r-before-you-start.html"><a href="what-you-need-to-be-able-to-do-in-r-before-you-start.html#installing-r-and-rstudio"><i class="fa fa-check"></i><b>2.1</b> Installing R (and RStudio)</a></li>
<li class="chapter" data-level="2.2" data-path="what-you-need-to-be-able-to-do-in-r-before-you-start.html"><a href="what-you-need-to-be-able-to-do-in-r-before-you-start.html#setting-the-working-directory"><i class="fa fa-check"></i><b>2.2</b> Setting the working directory</a></li>
<li class="chapter" data-level="2.3" data-path="what-you-need-to-be-able-to-do-in-r-before-you-start.html"><a href="what-you-need-to-be-able-to-do-in-r-before-you-start.html#using-a-script"><i class="fa fa-check"></i><b>2.3</b> Using a script</a></li>
<li class="chapter" data-level="2.4" data-path="what-you-need-to-be-able-to-do-in-r-before-you-start.html"><a href="what-you-need-to-be-able-to-do-in-r-before-you-start.html#installing-and-loading-extra-packages-in-r"><i class="fa fa-check"></i><b>2.4</b> Installing and loading extra packages in R</a></li>
<li class="chapter" data-level="2.5" data-path="what-you-need-to-be-able-to-do-in-r-before-you-start.html"><a href="what-you-need-to-be-able-to-do-in-r-before-you-start.html#loading-and-viewing-your-data-in-r"><i class="fa fa-check"></i><b>2.5</b> Loading and viewing your data in R</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="diversity-indices-in-r.html"><a href="diversity-indices-in-r.html"><i class="fa fa-check"></i><b>3</b> Diversity Indices in R</a><ul>
<li class="chapter" data-level="3.1" data-path="diversity-indices-in-r.html"><a href="diversity-indices-in-r.html#what-are-diversity-indices"><i class="fa fa-check"></i><b>3.1</b> What are diversity indices?</a><ul>
<li class="chapter" data-level="3.1.1" data-path="diversity-indices-in-r.html"><a href="diversity-indices-in-r.html#alpha-beta-and-gamma-diversity-whittaker-1960-1972"><i class="fa fa-check"></i><b>3.1.1</b> <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta\)</span> and <span class="math inline">\(\gamma\)</span> diversity (Whittaker 1960, 1972)</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="diversity-indices-in-r.html"><a href="diversity-indices-in-r.html#practical-example-using-pokemon"><i class="fa fa-check"></i><b>3.2</b> Practical example using Pokemon…</a></li>
<li class="chapter" data-level="3.3" data-path="diversity-indices-in-r.html"><a href="diversity-indices-in-r.html#species-diversity-indices"><i class="fa fa-check"></i><b>3.3</b> Species diversity indices</a><ul>
<li class="chapter" data-level="3.3.1" data-path="diversity-indices-in-r.html"><a href="diversity-indices-in-r.html#alpha-diversity"><i class="fa fa-check"></i><b>3.3.1</b> <span class="math inline">\(\alpha\)</span> diversity</a></li>
<li class="chapter" data-level="3.3.2" data-path="diversity-indices-in-r.html"><a href="diversity-indices-in-r.html#beta-diversity"><i class="fa fa-check"></i><b>3.3.2</b> <span class="math inline">\(\beta\)</span> diversity</a></li>
<li class="chapter" data-level="3.3.3" data-path="diversity-indices-in-r.html"><a href="diversity-indices-in-r.html#gamma-diversity"><i class="fa fa-check"></i><b>3.3.3</b> <span class="math inline">\(\gamma\)</span> diversity</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="diversity-indices-in-r.html"><a href="diversity-indices-in-r.html#species-accumulation-curves-colwell-coddington-1994"><i class="fa fa-check"></i><b>3.4</b> Species accumulation curves (Colwell &amp; Coddington 1994)</a><ul>
<li class="chapter" data-level="3.4.1" data-path="diversity-indices-in-r.html"><a href="diversity-indices-in-r.html#practical-example"><i class="fa fa-check"></i><b>3.4.1</b> Practical example</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="diversity-indices-in-r.html"><a href="diversity-indices-in-r.html#references"><i class="fa fa-check"></i><b>3.5</b> References</a><ul>
<li class="chapter" data-level="3.5.1" data-path="diversity-indices-in-r.html"><a href="diversity-indices-in-r.html#extra-reading"><i class="fa fa-check"></i><b>3.5.1</b> Extra reading</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="visualising-phylogenies-in-r.html"><a href="visualising-phylogenies-in-r.html"><i class="fa fa-check"></i><b>4</b> Visualising phylogenies in R</a><ul>
<li class="chapter" data-level="4.1" data-path="visualising-phylogenies-in-r.html"><a href="visualising-phylogenies-in-r.html#loading-your-phylogeny-and-data-into-r"><i class="fa fa-check"></i><b>4.1</b> Loading your phylogeny and data into R</a><ul>
<li class="chapter" data-level="4.1.1" data-path="visualising-phylogenies-in-r.html"><a href="visualising-phylogenies-in-r.html#reading-in-a-phylogeny-from-a-file"><i class="fa fa-check"></i><b>4.1.1</b> Reading in a phylogeny from a file</a></li>
<li class="chapter" data-level="4.1.2" data-path="visualising-phylogenies-in-r.html"><a href="visualising-phylogenies-in-r.html#reading-in-a-phylogeny-that-is-already-built-into-r"><i class="fa fa-check"></i><b>4.1.2</b> Reading in a phylogeny that is already built into R</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="visualising-phylogenies-in-r.html"><a href="visualising-phylogenies-in-r.html#basic-tree-viewing-in-r"><i class="fa fa-check"></i><b>4.2</b> Basic tree viewing in R</a></li>
<li class="chapter" data-level="4.3" data-path="visualising-phylogenies-in-r.html"><a href="visualising-phylogenies-in-r.html#adding-trait-data-to-trees-in-r"><i class="fa fa-check"></i><b>4.3</b> Adding trait data to trees in R</a><ul>
<li class="chapter" data-level="4.3.1" data-path="visualising-phylogenies-in-r.html"><a href="visualising-phylogenies-in-r.html#ancestral-state-reconstructions-on-continuous-data"><i class="fa fa-check"></i><b>4.3.1</b> Ancestral state reconstructions on continuous data</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="visualising-phylogenies-in-r.html"><a href="visualising-phylogenies-in-r.html#phylomorphospace-plots-in-r"><i class="fa fa-check"></i><b>4.4</b> Phylomorphospace plots in R</a></li>
<li class="chapter" data-level="4.5" data-path="visualising-phylogenies-in-r.html"><a href="visualising-phylogenies-in-r.html#phylogenies-and-maps"><i class="fa fa-check"></i><b>4.5</b> Phylogenies and maps!</a></li>
<li class="chapter" data-level="4.6" data-path="visualising-phylogenies-in-r.html"><a href="visualising-phylogenies-in-r.html#a-new-package-for-visualising-trees-ggtree"><i class="fa fa-check"></i><b>4.6</b> A new package for visualising trees: ggtree</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="phylogenetic-generalised-least-squares-pgls-in-r.html"><a href="phylogenetic-generalised-least-squares-pgls-in-r.html"><i class="fa fa-check"></i><b>5</b> Phylogenetic Generalised Least Squares (PGLS) in R</a><ul>
<li class="chapter" data-level="5.1" data-path="phylogenetic-generalised-least-squares-pgls-in-r.html"><a href="phylogenetic-generalised-least-squares-pgls-in-r.html#preparing-for-the-analysis"><i class="fa fa-check"></i><b>5.1</b> Preparing for the analysis</a><ul>
<li class="chapter" data-level="5.1.1" data-path="phylogenetic-generalised-least-squares-pgls-in-r.html"><a href="phylogenetic-generalised-least-squares-pgls-in-r.html#load-the-required-packages"><i class="fa fa-check"></i><b>5.1.1</b> Load the required packages</a></li>
<li class="chapter" data-level="5.1.2" data-path="phylogenetic-generalised-least-squares-pgls-in-r.html"><a href="phylogenetic-generalised-least-squares-pgls-in-r.html#reading-and-checking-your-data-in-r"><i class="fa fa-check"></i><b>5.1.2</b> Reading and checking your data in R</a></li>
<li class="chapter" data-level="5.1.3" data-path="phylogenetic-generalised-least-squares-pgls-in-r.html"><a href="phylogenetic-generalised-least-squares-pgls-in-r.html#reading-and-checking-your-phylogeny-in-r"><i class="fa fa-check"></i><b>5.1.3</b> Reading and checking your phylogeny in R</a></li>
<li class="chapter" data-level="5.1.4" data-path="phylogenetic-generalised-least-squares-pgls-in-r.html"><a href="phylogenetic-generalised-least-squares-pgls-in-r.html#manipulating-your-data-and-phylogeny-in-r"><i class="fa fa-check"></i><b>5.1.4</b> Manipulating your data and phylogeny in R</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="phylogenetic-generalised-least-squares-pgls-in-r.html"><a href="phylogenetic-generalised-least-squares-pgls-in-r.html#ordinary-least-squares-ols-regression"><i class="fa fa-check"></i><b>5.2</b> Ordinary least squares (OLS) regression</a></li>
<li class="chapter" data-level="5.3" data-path="phylogenetic-generalised-least-squares-pgls-in-r.html"><a href="phylogenetic-generalised-least-squares-pgls-in-r.html#phylogenetic-generalized-least-squares-models-pgls"><i class="fa fa-check"></i><b>5.3</b> Phylogenetic generalized least squares models (PGLS)</a><ul>
<li class="chapter" data-level="5.3.1" data-path="phylogenetic-generalised-least-squares-pgls-in-r.html"><a href="phylogenetic-generalised-least-squares-pgls-in-r.html#likelihood-profiles-for-lambda-in-pgls-models"><i class="fa fa-check"></i><b>5.3.1</b> Likelihood profiles for <span class="math inline">\(\lambda\)</span> in PGLS models</a></li>
<li class="chapter" data-level="5.3.2" data-path="phylogenetic-generalised-least-squares-pgls-in-r.html"><a href="phylogenetic-generalised-least-squares-pgls-in-r.html#model-diagnostics-for-pgls-models"><i class="fa fa-check"></i><b>5.3.2</b> Model diagnostics for PGLS models</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="phylogenetic-generalised-least-squares-pgls-in-r.html"><a href="phylogenetic-generalised-least-squares-pgls-in-r.html#estimating-phylogenetic-signal-for-one-variable"><i class="fa fa-check"></i><b>5.4</b> Estimating phylogenetic signal for one variable</a><ul>
<li class="chapter" data-level="5.4.1" data-path="phylogenetic-generalised-least-squares-pgls-in-r.html"><a href="phylogenetic-generalised-least-squares-pgls-in-r.html#pagels-lambda-pagel-19971999-freckleton-et-al-2002"><i class="fa fa-check"></i><b>5.4.1</b> Pagel’s <span class="math inline">\(\lambda\)</span> (Pagel 1997/1999, Freckleton et al 2002)</a></li>
<li class="chapter" data-level="5.4.2" data-path="phylogenetic-generalised-least-squares-pgls-in-r.html"><a href="phylogenetic-generalised-least-squares-pgls-in-r.html#blombergs-k-blomberg-et-al-2003"><i class="fa fa-check"></i><b>5.4.2</b> Blomberg’s K (Blomberg et al 2003)</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="phylogenetic-generalised-least-squares-pgls-in-r.html"><a href="phylogenetic-generalised-least-squares-pgls-in-r.html#references-1"><i class="fa fa-check"></i><b>5.5</b> References</a><ul>
<li class="chapter" data-level="5.5.1" data-path="phylogenetic-generalised-least-squares-pgls-in-r.html"><a href="phylogenetic-generalised-least-squares-pgls-in-r.html#extra-reading-1"><i class="fa fa-check"></i><b>5.5.1</b> Extra Reading</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="macroevolutionary-models-in-r-part-1-continuous-traits.html"><a href="macroevolutionary-models-in-r-part-1-continuous-traits.html"><i class="fa fa-check"></i><b>6</b> Macroevolutionary models in R: Part 1 - continuous traits</a><ul>
<li class="chapter" data-level="6.1" data-path="macroevolutionary-models-in-r-part-1-continuous-traits.html"><a href="macroevolutionary-models-in-r-part-1-continuous-traits.html#preparing-for-the-analysis-1"><i class="fa fa-check"></i><b>6.1</b> Preparing for the analysis</a><ul>
<li class="chapter" data-level="6.1.1" data-path="macroevolutionary-models-in-r-part-1-continuous-traits.html"><a href="macroevolutionary-models-in-r-part-1-continuous-traits.html#load-packages-read-in-the-data-and-the-tree"><i class="fa fa-check"></i><b>6.1.1</b> Load packages, read in the data and the tree</a></li>
<li class="chapter" data-level="6.1.2" data-path="macroevolutionary-models-in-r-part-1-continuous-traits.html"><a href="macroevolutionary-models-in-r-part-1-continuous-traits.html#modify-the-tree-and-data-so-they-can-be-used-in-the-analyses."><i class="fa fa-check"></i><b>6.1.2</b> Modify the tree and data so they can be used in the analyses.</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="macroevolutionary-models-in-r-part-1-continuous-traits.html"><a href="macroevolutionary-models-in-r-part-1-continuous-traits.html#models-of-continuous-trait-evolution"><i class="fa fa-check"></i><b>6.2</b> Models of continuous trait evolution</a><ul>
<li class="chapter" data-level="6.2.1" data-path="macroevolutionary-models-in-r-part-1-continuous-traits.html"><a href="macroevolutionary-models-in-r-part-1-continuous-traits.html#the-brownian-motion-bm-model"><i class="fa fa-check"></i><b>6.2.1</b> The Brownian motion (BM model)</a></li>
<li class="chapter" data-level="6.2.2" data-path="macroevolutionary-models-in-r-part-1-continuous-traits.html"><a href="macroevolutionary-models-in-r-part-1-continuous-traits.html#the-ornstein-uhlenbeck-ou-model"><i class="fa fa-check"></i><b>6.2.2</b> The Ornstein-Uhlenbeck (OU) model</a></li>
<li class="chapter" data-level="6.2.3" data-path="macroevolutionary-models-in-r-part-1-continuous-traits.html"><a href="macroevolutionary-models-in-r-part-1-continuous-traits.html#the-early-burst-eb-model"><i class="fa fa-check"></i><b>6.2.3</b> The Early Burst (EB) model</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="macroevolutionary-models-in-r-part-1-continuous-traits.html"><a href="macroevolutionary-models-in-r-part-1-continuous-traits.html#fitting-the-models-using-fitcontinuous"><i class="fa fa-check"></i><b>6.3</b> Fitting the models using <code>fitContinuous</code></a><ul>
<li class="chapter" data-level="6.3.1" data-path="macroevolutionary-models-in-r-part-1-continuous-traits.html"><a href="macroevolutionary-models-in-r-part-1-continuous-traits.html#comparing-models-of-evolution"><i class="fa fa-check"></i><b>6.3.1</b> Comparing models of evolution</a></li>
<li class="chapter" data-level="6.3.2" data-path="macroevolutionary-models-in-r-part-1-continuous-traits.html"><a href="macroevolutionary-models-in-r-part-1-continuous-traits.html#problems-with-convergence-and-bounds"><i class="fa fa-check"></i><b>6.3.2</b> Problems with convergence and bounds</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="macroevolutionary-models-in-r-part-1-continuous-traits.html"><a href="macroevolutionary-models-in-r-part-1-continuous-traits.html#references-2"><i class="fa fa-check"></i><b>6.4</b> References</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="macroevolutionary-models-in-r-part-2-discrete-traits.html"><a href="macroevolutionary-models-in-r-part-2-discrete-traits.html"><i class="fa fa-check"></i><b>7</b> Macroevolutionary models in R: Part 2 - discrete traits</a><ul>
<li class="chapter" data-level="7.1" data-path="macroevolutionary-models-in-r-part-2-discrete-traits.html"><a href="macroevolutionary-models-in-r-part-2-discrete-traits.html#preparing-for-the-analysis-2"><i class="fa fa-check"></i><b>7.1</b> Preparing for the analysis</a><ul>
<li class="chapter" data-level="7.1.1" data-path="macroevolutionary-models-in-r-part-2-discrete-traits.html"><a href="macroevolutionary-models-in-r-part-2-discrete-traits.html#load-packages-read-in-the-data-and-the-tree-1"><i class="fa fa-check"></i><b>7.1.1</b> Load packages, read in the data and the tree</a></li>
<li class="chapter" data-level="7.1.2" data-path="macroevolutionary-models-in-r-part-2-discrete-traits.html"><a href="macroevolutionary-models-in-r-part-2-discrete-traits.html#modify-the-tree-and-data-so-they-can-be-used-in-the-analyses.-1"><i class="fa fa-check"></i><b>7.1.2</b> Modify the tree and data so they can be used in the analyses.</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="macroevolutionary-models-in-r-part-2-discrete-traits.html"><a href="macroevolutionary-models-in-r-part-2-discrete-traits.html#fitting-models-of-evolution-to-discrete-data-regime-dependent-evolution"><i class="fa fa-check"></i><b>7.2</b> Fitting models of evolution to discrete data (regime dependent evolution)</a></li>
<li class="chapter" data-level="7.3" data-path="macroevolutionary-models-in-r-part-2-discrete-traits.html"><a href="macroevolutionary-models-in-r-part-2-discrete-traits.html#models-of-discrete-trait-evolution"><i class="fa fa-check"></i><b>7.3</b> Models of discrete trait evolution</a><ul>
<li class="chapter" data-level="7.3.1" data-path="macroevolutionary-models-in-r-part-2-discrete-traits.html"><a href="macroevolutionary-models-in-r-part-2-discrete-traits.html#mk1-all-rates-equal-er"><i class="fa fa-check"></i><b>7.3.1</b> Mk1 – all rates equal (ER)</a></li>
<li class="chapter" data-level="7.3.2" data-path="macroevolutionary-models-in-r-part-2-discrete-traits.html"><a href="macroevolutionary-models-in-r-part-2-discrete-traits.html#mk-symmetric-rates-sym"><i class="fa fa-check"></i><b>7.3.2</b> Mk – symmetric rates (SYM)</a></li>
<li class="chapter" data-level="7.3.3" data-path="macroevolutionary-models-in-r-part-2-discrete-traits.html"><a href="macroevolutionary-models-in-r-part-2-discrete-traits.html#mk-all-rates-different-ard"><i class="fa fa-check"></i><b>7.3.3</b> Mk – All Rates Different (ARD)</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="macroevolutionary-models-in-r-part-2-discrete-traits.html"><a href="macroevolutionary-models-in-r-part-2-discrete-traits.html#fitting-the-models-using-fitdiscrete"><i class="fa fa-check"></i><b>7.4</b> Fitting the models using <code>fitDiscrete</code></a></li>
<li class="chapter" data-level="7.5" data-path="macroevolutionary-models-in-r-part-2-discrete-traits.html"><a href="macroevolutionary-models-in-r-part-2-discrete-traits.html#ancestral-state-reconstructions"><i class="fa fa-check"></i><b>7.5</b> Ancestral state reconstructions</a></li>
<li class="chapter" data-level="7.6" data-path="macroevolutionary-models-in-r-part-2-discrete-traits.html"><a href="macroevolutionary-models-in-r-part-2-discrete-traits.html#fitting-models-using-ouwie"><i class="fa fa-check"></i><b>7.6</b> Fitting models using <code>OUwie</code></a><ul>
<li class="chapter" data-level="7.6.1" data-path="macroevolutionary-models-in-r-part-2-discrete-traits.html"><a href="macroevolutionary-models-in-r-part-2-discrete-traits.html#multi-rate-brownian-motion-bms"><i class="fa fa-check"></i><b>7.6.1</b> Multi-rate Brownian motion (BMS)</a></li>
<li class="chapter" data-level="7.6.2" data-path="macroevolutionary-models-in-r-part-2-discrete-traits.html"><a href="macroevolutionary-models-in-r-part-2-discrete-traits.html#multi-peak-ou-models"><i class="fa fa-check"></i><b>7.6.2</b> Multi-peak OU models</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="macroevolutionary-models-in-r-part-2-discrete-traits.html"><a href="macroevolutionary-models-in-r-part-2-discrete-traits.html#references-3"><i class="fa fa-check"></i><b>7.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="geometric-morphometrics-in-r.html"><a href="geometric-morphometrics-in-r.html"><i class="fa fa-check"></i><b>8</b> Geometric Morphometrics in R</a><ul>
<li class="chapter" data-level="8.1" data-path="geometric-morphometrics-in-r.html"><a href="geometric-morphometrics-in-r.html#a-quick-introduction-to-geometric-morphometrics"><i class="fa fa-check"></i><b>8.1</b> A quick introduction to geometric morphometrics</a><ul>
<li class="chapter" data-level="8.1.1" data-path="geometric-morphometrics-in-r.html"><a href="geometric-morphometrics-in-r.html#what-is-morphometrics"><i class="fa fa-check"></i><b>8.1.1</b> What is morphometrics?</a></li>
<li class="chapter" data-level="8.1.2" data-path="geometric-morphometrics-in-r.html"><a href="geometric-morphometrics-in-r.html#landmarks"><i class="fa fa-check"></i><b>8.1.2</b> Landmarks</a></li>
<li class="chapter" data-level="8.1.3" data-path="geometric-morphometrics-in-r.html"><a href="geometric-morphometrics-in-r.html#collecting-data-and-adding-landmarks"><i class="fa fa-check"></i><b>8.1.3</b> Collecting data and adding landmarks</a></li>
<li class="chapter" data-level="8.1.4" data-path="geometric-morphometrics-in-r.html"><a href="geometric-morphometrics-in-r.html#measurement-error"><i class="fa fa-check"></i><b>8.1.4</b> Measurement error</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="geometric-morphometrics-in-r.html"><a href="geometric-morphometrics-in-r.html#a-practical-example-using-r"><i class="fa fa-check"></i><b>8.2</b> A practical example using R</a></li>
<li class="chapter" data-level="8.3" data-path="geometric-morphometrics-in-r.html"><a href="geometric-morphometrics-in-r.html#gathering-the-data"><i class="fa fa-check"></i><b>8.3</b> Gathering the data</a></li>
<li class="chapter" data-level="8.4" data-path="geometric-morphometrics-in-r.html"><a href="geometric-morphometrics-in-r.html#digitising-adding-landmarks-and-curves"><i class="fa fa-check"></i><b>8.4</b> Digitising (adding landmarks and curves)</a></li>
<li class="chapter" data-level="8.5" data-path="geometric-morphometrics-in-r.html"><a href="geometric-morphometrics-in-r.html#reading-in-your-data-and-plotting-it"><i class="fa fa-check"></i><b>8.5</b> Reading in your data and plotting it</a></li>
<li class="chapter" data-level="8.6" data-path="geometric-morphometrics-in-r.html"><a href="geometric-morphometrics-in-r.html#generalised-procrustes-superimposition-gpa"><i class="fa fa-check"></i><b>8.6</b> Generalised Procrustes Superimposition (GPA)</a></li>
<li class="chapter" data-level="8.7" data-path="geometric-morphometrics-in-r.html"><a href="geometric-morphometrics-in-r.html#principal-components-and-plotting"><i class="fa fa-check"></i><b>8.7</b> Principal components and plotting</a></li>
<li class="chapter" data-level="8.8" data-path="geometric-morphometrics-in-r.html"><a href="geometric-morphometrics-in-r.html#statistical-analyses-of-geometric-morphometric-datasets"><i class="fa fa-check"></i><b>8.8</b> Statistical analyses of geometric morphometric datasets</a></li>
<li class="chapter" data-level="8.9" data-path="geometric-morphometrics-in-r.html"><a href="geometric-morphometrics-in-r.html#regression"><i class="fa fa-check"></i><b>8.9</b> Regression</a></li>
<li class="chapter" data-level="8.10" data-path="geometric-morphometrics-in-r.html"><a href="geometric-morphometrics-in-r.html#multivariate-regression"><i class="fa fa-check"></i><b>8.10</b> Multivariate regression</a></li>
<li class="chapter" data-level="8.11" data-path="geometric-morphometrics-in-r.html"><a href="geometric-morphometrics-in-r.html#anova"><i class="fa fa-check"></i><b>8.11</b> ANOVA</a></li>
<li class="chapter" data-level="8.12" data-path="geometric-morphometrics-in-r.html"><a href="geometric-morphometrics-in-r.html#manova"><i class="fa fa-check"></i><b>8.12</b> MANOVA</a></li>
<li class="chapter" data-level="8.13" data-path="geometric-morphometrics-in-r.html"><a href="geometric-morphometrics-in-r.html#resources-for-learning-geometric-morphometrics"><i class="fa fa-check"></i><b>8.13</b> Resources for learning geometric morphometrics</a></li>
<li class="chapter" data-level="8.14" data-path="geometric-morphometrics-in-r.html"><a href="geometric-morphometrics-in-r.html#references-4"><i class="fa fa-check"></i><b>8.14</b> References</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html"><a href="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html"><i class="fa fa-check"></i><b>9</b> BAMM: Bayesian Analysis of Macroevolutionary Mixtures</a><ul>
<li class="chapter" data-level="9.1" data-path="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html"><a href="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html#a-quick-intro-to-bamm"><i class="fa fa-check"></i><b>9.1</b> A quick intro to BAMM</a></li>
<li class="chapter" data-level="9.2" data-path="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html"><a href="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html#a-brief-aside-how-do-i-run-bamm"><i class="fa fa-check"></i><b>9.2</b> A brief aside: how do I run BAMM?</a></li>
<li class="chapter" data-level="9.3" data-path="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html"><a href="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html#what-does-a-bamm-analysis-produce"><i class="fa fa-check"></i><b>9.3</b> What does a BAMM analysis produce?</a><ul>
<li class="chapter" data-level="9.3.1" data-path="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html"><a href="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html#distinct-shift-configurations-and-how-to-summarise-them"><i class="fa fa-check"></i><b>9.3.1</b> Distinct shift configurations and how to summarise them</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html"><a href="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html#a-practical-example-looking-at-bamm-results-using-bammtools"><i class="fa fa-check"></i><b>9.4</b> A practical example looking at BAMM results using <code>BAMMtools</code></a></li>
<li class="chapter" data-level="9.5" data-path="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html"><a href="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html#assessing-mcmc-convergence"><i class="fa fa-check"></i><b>9.5</b> Assessing MCMC convergence</a></li>
<li class="chapter" data-level="9.6" data-path="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html"><a href="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html#analysis-of-rate-shifts-in-marsupial-phylogeny"><i class="fa fa-check"></i><b>9.6</b> Analysis of rate shifts in marsupial phylogeny</a><ul>
<li class="chapter" data-level="9.6.1" data-path="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html"><a href="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html#how-many-rate-shifts"><i class="fa fa-check"></i><b>9.6.1</b> How many rate shifts?</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html"><a href="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html#mean-phylorate-plot"><i class="fa fa-check"></i><b>9.7</b> Mean phylorate plot</a></li>
<li class="chapter" data-level="9.8" data-path="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html"><a href="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html#best-single-distinct-shift-configuration"><i class="fa fa-check"></i><b>9.8</b> Best single distinct shift configuration</a></li>
<li class="chapter" data-level="9.9" data-path="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html"><a href="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html#credible-sets-of-shifts"><i class="fa fa-check"></i><b>9.9</b> Credible sets of shifts</a></li>
<li class="chapter" data-level="9.10" data-path="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html"><a href="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html#clade-specific-evolutionary-rates"><i class="fa fa-check"></i><b>9.10</b> Clade specific evolutionary rates</a></li>
<li class="chapter" data-level="9.11" data-path="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html"><a href="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html#rate-through-time-analysis"><i class="fa fa-check"></i><b>9.11</b> Rate-through-time analysis</a></li>
<li class="chapter" data-level="9.12" data-path="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html"><a href="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html#macroevolutionary-cohort-analysis"><i class="fa fa-check"></i><b>9.12</b> Macroevolutionary cohort analysis</a></li>
<li class="chapter" data-level="9.13" data-path="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html"><a href="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html#assumptions-and-issues-with-bamm"><i class="fa fa-check"></i><b>9.13</b> Assumptions and issues with BAMM</a></li>
<li class="chapter" data-level="9.14" data-path="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html"><a href="bamm-bayesian-analysis-of-macroevolutionary-mixtures.html#references-5"><i class="fa fa-check"></i><b>9.14</b> References</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="critical-thinking-about-methods-and-analyses.html"><a href="critical-thinking-about-methods-and-analyses.html"><i class="fa fa-check"></i><b>10</b> Critical thinking about methods and analyses</a><ul>
<li class="chapter" data-level="10.1" data-path="critical-thinking-about-methods-and-analyses.html"><a href="critical-thinking-about-methods-and-analyses.html#how-to-critically-evaluate-a-paper"><i class="fa fa-check"></i><b>10.1</b> How to critically evaluate a paper</a><ul>
<li class="chapter" data-level="10.1.1" data-path="critical-thinking-about-methods-and-analyses.html"><a href="critical-thinking-about-methods-and-analyses.html#logicinterpretation"><i class="fa fa-check"></i><b>10.1.1</b> Logic/interpretation</a></li>
<li class="chapter" data-level="10.1.2" data-path="critical-thinking-about-methods-and-analyses.html"><a href="critical-thinking-about-methods-and-analyses.html#data"><i class="fa fa-check"></i><b>10.1.2</b> Data</a></li>
<li class="chapter" data-level="10.1.3" data-path="critical-thinking-about-methods-and-analyses.html"><a href="critical-thinking-about-methods-and-analyses.html#methods"><i class="fa fa-check"></i><b>10.1.3</b> Methods</a></li>
<li class="chapter" data-level="10.1.4" data-path="critical-thinking-about-methods-and-analyses.html"><a href="critical-thinking-about-methods-and-analyses.html#moving-forwards"><i class="fa fa-check"></i><b>10.1.4</b> Moving forwards</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="critical-thinking-about-methods-and-analyses.html"><a href="critical-thinking-about-methods-and-analyses.html#references-6"><i class="fa fa-check"></i><b>10.2</b> References</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="practice-questions.html"><a href="practice-questions.html"><i class="fa fa-check"></i><b>11</b> Practice Questions</a><ul>
<li class="chapter" data-level="11.1" data-path="practice-questions.html"><a href="practice-questions.html#diversity-indices-in-r-1"><i class="fa fa-check"></i><b>11.1</b> Diversity indices in R</a></li>
<li class="chapter" data-level="11.2" data-path="practice-questions.html"><a href="practice-questions.html#pgls-in-r"><i class="fa fa-check"></i><b>11.2</b> PGLS in R</a></li>
<li class="chapter" data-level="11.3" data-path="practice-questions.html"><a href="practice-questions.html#macroevolutionary-models"><i class="fa fa-check"></i><b>11.3</b> Macroevolutionary models</a></li>
<li class="chapter" data-level="11.4" data-path="practice-questions.html"><a href="practice-questions.html#geometric-morphometrics"><i class="fa fa-check"></i><b>11.4</b> Geometric morphometrics</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/nhcooper123/TeachingMaterials/MSc_Museum/MacroModule" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Methods in Macroecology and Macroevolution</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="macroevolutionary-models-in-r-part-1---continuous-traits" class="section level1">
<h1><span class="header-section-number">Practical 6</span> Macroevolutionary models in R: Part 1 - continuous traits</h1>
<p>The aims of this practical are to learn how to use R to fit macroevolutionary models in R to continuous traits.</p>
<p>We will be using the evolution of magical creature life-history variables as an example. The data includes body mass (average adult size at rest) in kg, social status (1 = solitary, 2 = social), habitat (1 = terrestrial, 2 = aquatic, 3 = volant) and magical power (in thaum - with thanks to Terry Pratchett for the units). These data are invented, so please don’t get too upset if I’ve misclassified anything!</p>
<p><strong>REMEMBER</strong></p>
<ul>
<li>Download all of the data for the practical into a folder somewhere on your computer.</li>
<li>Set your working directory to this folder.</li>
<li>Start a new script for this practical.</li>
</ul>
<p>You will also need to install the following packages:</p>
<ul>
<li><code>ape</code></li>
<li><code>geiger</code></li>
<li><code>OUwie</code></li>
</ul>
<p>This practical is in two parts, Part 2 deals with discrete traits.</p>
<hr />
<div id="preparing-for-the-analysis-1" class="section level2">
<h2><span class="header-section-number">6.1</span> Preparing for the analysis</h2>
<div id="load-packages-read-in-the-data-and-the-tree" class="section level3">
<h3><span class="header-section-number">6.1.1</span> Load packages, read in the data and the tree</h3>
<p>This is the same as we did in the PGLS practical, so I won’t give detailed instructions here.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Load packages</span>
<span class="kw">library</span>(ape)
<span class="kw">library</span>(geiger)
<span class="kw">library</span>(OUwie)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Read in data</span>
magicaldata &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;magicalcreatures.csv&quot;</span>)
<span class="co"># Check data is loaded correctly</span>
<span class="kw">str</span>(magicaldata)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    30 obs. of  5 variables:
##  $ Species     : Factor w/ 30 levels &quot;Acromantula&quot;,..: 22 24 19 5 7 16 21 25 30 29 ...
##  $ BodySize_kg : num  1.5 50 0.5 100 8000 1 2.5 6 800 600 ...
##  $ SocialStatus: int  2 2 2 1 1 2 2 1 1 2 ...
##  $ Habitat     : int  1 1 2 1 3 1 1 3 3 3 ...
##  $ Magic_thaum : num  106.3 86.7 98.6 57 131.9 ...</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Read in tree</span>
magicaltree &lt;-<span class="st"> </span><span class="kw">read.nexus</span>(<span class="st">&quot;magicaltree.nex&quot;</span>) 
<span class="co"># Check tree is loaded correctly</span>
<span class="kw">str</span>(magicaltree)</code></pre></div>
<pre><code>## List of 4
##  $ edge       : int [1:52, 1:2] 28 29 30 31 31 30 32 33 33 34 ...
##  $ edge.length: num [1:52] 136.86 65.69 97 2.92 2.92 ...
##  $ Nnode      : int 26
##  $ tip.label  : chr [1:27] &quot;Doxie&quot; &quot;Bowtruckle&quot; &quot;Hinkypuff&quot; &quot;Grindylow&quot; ...
##  - attr(*, &quot;class&quot;)= chr &quot;phylo&quot;
##  - attr(*, &quot;order&quot;)= chr &quot;cladewise&quot;</code></pre>
</div>
<div id="modify-the-tree-and-data-so-they-can-be-used-in-the-analyses." class="section level3">
<h3><span class="header-section-number">6.1.2</span> Modify the tree and data so they can be used in the analyses.</h3>
<p>Again we did this in the PGLS practical. Please remind yourself of what these steps are needed for.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Ensure tree is fully bifurcating</span>
magicaltree &lt;-<span class="st"> </span><span class="kw">multi2di</span>(magicaltree) 

<span class="co"># Replace spaces with underscores in the species names</span>
magicaldata$Species &lt;-<span class="st"> </span><span class="kw">gsub</span>(<span class="st">&quot; &quot;</span>, <span class="st">&quot;_&quot;</span>, magicaldata$Species)

<span class="co"># Add species names to row names</span>
<span class="kw">row.names</span>(magicaldata) &lt;-<span class="st"> </span>magicaldata$Species</code></pre></div>
<p>For some weird reason the <code>geiger</code> function we need (<code>treedata</code> see below) won’t work if you input a dataset with variables that are characters i.e. words or letters. Our taxonomic variable Species is a character so we need to exclude it from the data. Note for your own data you’d need to remove all character variables (or recode them as 0,12 etc.). We will do this by making a new dataset called magicaldata2.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">magicaldata2 &lt;-<span class="st"> </span>magicaldata[, <span class="dv">2</span>:<span class="dv">5</span>]</code></pre></div>
<p>Here the [ ] tells R we want to subset the dataset. R data frames are always described by [X,Y] where X is rows and Y is columns. So [1, 1] will select the entry in the first column and the first row of the data frame. [, 2:2] selects all rows but only columns 2 to 5. These are the columns containing our numeric variables.</p>
<p>We then need to match the species in tree to those in the dataset as in the PGLS practical. <strong>Note that we are using <code>magicaldata2</code> here.</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">match.species &lt;-<span class="st"> </span><span class="kw">treedata</span>(magicaltree, magicaldata2)

mytree &lt;-<span class="st"> </span>match.species$phy
mydata &lt;-<span class="st"> </span>match.species$data</code></pre></div>
<hr />
</div>
</div>
<div id="models-of-continuous-trait-evolution" class="section level2">
<h2><span class="header-section-number">6.2</span> Models of continuous trait evolution</h2>
<p>For fitting models of evolution to continuous data we will use the <code>fitContinuous</code> function in the R package <code>geiger</code>. <code>fitContinuous</code> is a likelihood based method, so the output will give the maximum likelihood (ML) estimates of the parameters. Bayesian methods are becoming preferred for these kinds of analyses and <code>fitContinuousMCMC</code> will perform these analyses. However, due to time constraints we will not cover this function. As an example, let’s look at the evolution of <code>log(body size)</code> in magical creatures. We’ll fit three evolutionary models – the Brownian motion (BM) model, the Ornstein-Uhlenbeck (OU) model and the Early Burst (EB) model. <code>fitContinuous</code> can also fit several other models. For more details look at the help file by typing: <code>?fitContinuous</code></p>
<div id="the-brownian-motion-bm-model" class="section level3">
<h3><span class="header-section-number">6.2.1</span> The Brownian motion (BM model)</h3>
<p>The Brownian motion model (Cavalli-Sforza and Edwards, 1967; Felsenstein, 1973) is assumed to be the underlying mode of evolution in the majority of phylogenetic comparative methods (though this assumption is rarely tested; Freckleton and Harvey 2006). In the model, a trait <span class="math inline">\(X\)</span> evolves at random at a rate <span class="math inline">\(\sigma\)</span>:</p>
<p><span class="math inline">\(dX(t) = \sigma dW(t)\)</span></p>
<p>where <span class="math inline">\(W(t)\)</span> is a white noise function and is a random variate drawn from a normal distribution with mean 0 and variance <span class="math inline">\(\sigma^2\)</span>. This model assumes that there is no overall drift in the direction of evolution (hence the expectation of <span class="math inline">\(W(t)\)</span> is zero) and that the rate of evolution is constant. Because the direction of change in trait values at each step is random, Brownian motion is often described as a “random walk” (note that you can also fit models where <span class="math inline">\(W(t)\)</span> is not zero and there is drift in the direction of evolution. This is known as the drift model, or Brownian motion with a trend. We will not cover this here).</p>
<p>The model assumes the correlation structure among trait values is proportional to the extent of shared ancestry for pairs of species. This means that close relatives will be more similar in their trait values than more distant relatives. It also means that variance in the trait will increase (linearly) in proportion to time. The model has two parameters, the Brownian rate parameter, <span class="math inline">\(\sigma^2\)</span> and the state of the root at time zero, <span class="math inline">\(X(0)\)</span>. <code>fitContinuous</code> estimates <span class="math inline">\(\sigma^2\)</span> and <span class="math inline">\(X(0)\)</span>. Note that <span class="math inline">\(\sigma^2\)</span> can be used as a measure of the rate of trait evolution (Cooper and Purvis, 2010; Cooper et al., 2011).</p>
</div>
<div id="the-ornstein-uhlenbeck-ou-model" class="section level3">
<h3><span class="header-section-number">6.2.2</span> The Ornstein-Uhlenbeck (OU) model</h3>
<p>The Ornstein-Uhlenbeck (OU) model (Hansen, 1997; Butler and King, 2004) is a random walk where trait values are pulled back towards some “optimal” value with an attraction strength proportional to the parameter <span class="math inline">\(\alpha\)</span>. The model has the following form:</p>
<p><span class="math inline">\(dX(t) = -\alpha(X(t) - \mu) + \sigma dW(t)\)</span></p>
<p>Note that this model has two parameters in addition to those of the Brownian model, <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\mu\)</span>. The parameter m is a long-term mean, and it is assumed that species evolve around this value. <span class="math inline">\(\alpha\)</span> is the strength of evolutionary force that returns traits back towards the long-term mean if they evolve away from it. <span class="math inline">\(\alpha\)</span> is sometimes referred to as the “rubber band” parameter because of the way it forces traits back towards <span class="math inline">\(\mu\)</span>. The OU model was introduced to population genetics by Lande (1976) to model stabilizing selection in which the mean was recast as a fitness optimum on an adaptive landscape. The process operating in comparative data is analogous, although clearly is not stabilizing selection (despite being sometimes referred to as such). The model has four parameters, the Brownian rate parameter, <span class="math inline">\(\sigma^2\)</span>, the state of the root at time zero, <span class="math inline">\(X(0)\)</span>, the attraction strength or “rubber band” parameter, <span class="math inline">\(\alpha\)</span>, and the long-term mean, <span class="math inline">\(\mu\)</span>. <code>fitContinuous</code> estimates <span class="math inline">\(\sigma^2\)</span>, <span class="math inline">\(X(0)\)</span>, and <span class="math inline">\(\alpha\)</span>. It does not estimate <span class="math inline">\(\mu\)</span> but in this implementation of the model, <span class="math inline">\(\mu\)</span> is equivalent to <span class="math inline">\(X(0)\)</span>. Note that if <span class="math inline">\(\alpha\)</span> is close to zero then evolution is approximately Brownian.</p>
</div>
<div id="the-early-burst-eb-model" class="section level3">
<h3><span class="header-section-number">6.2.3</span> The Early Burst (EB) model</h3>
<p>The Early Burst (EB) model (Harmon et al. 2010, also called the ACDC model; Blomberg et al. 2003) is a Brownian motion/random walk model where the rate of evolution decreases exponentially through time under the model:</p>
<p><span class="math inline">\(r(t) = \sigma^2e(at)\)</span></p>
<p>Where <span class="math inline">\(r(t)\)</span> is the rate of evolution at time <span class="math inline">\(t\)</span>, <span class="math inline">\(\sigma^2\)</span> is the initial value of the Brownian rate parameter, i.e. the initial rate of evolution, <span class="math inline">\(a\)</span> is the rate change parameter, and <span class="math inline">\(t\)</span> is time. The value of <span class="math inline">\(a\)</span> is generally less than or equal to 0 (note that you can force <span class="math inline">\(a\)</span> to be greater than zero by changing the bounds - see section 3.4 - however, this will only work if you have fossil species in your data; Slater et al. 2012). When a is negative, rates of evolution decrease through time. The model fits traits where diversification occurs most rapidly early in a lineage and slows as the lineage approaches the present, so that subclades tend to retain their differences through time. This is consistent with a clade radiating adaptively into a fixed set of niches and has been used as evidence of niche-filling modes of evolution (Harmon et al., 2010; Cooper and Purvis, 2010). The model has three parameters, the Brownian rate parameter, <span class="math inline">\(\sigma^2\)</span>, the state of the root at time zero, <span class="math inline">\(X(0)\)</span>, and the rate of change parameter, <span class="math inline">\(a\)</span>. <code>fitContinuous</code> estimates <span class="math inline">\(\sigma^2\)</span>, <span class="math inline">\(X(0)\)</span> and <span class="math inline">\(a\)</span>. Note that if <span class="math inline">\(a\)</span> is close to zero then evolution is approximately Brownian. Note that although many people report a values when reporting the results of fitting an Early Burst model, it is often more intuitive to report the rate half-life, <span class="math inline">\(t_{\frac{1}{2}}\)</span> (Slater and Pennell, 2014). This is calculated as:</p>
<p><span class="math inline">\(t_{\frac{1}{2}} = \frac{log(2)}{|a|}\)</span></p>
<p>It can be interpreted as the time it takes for the rate of evolution of the trait to halve.</p>
</div>
</div>
<div id="fitting-the-models-using-fitcontinuous" class="section level2">
<h2><span class="header-section-number">6.3</span> Fitting the models using <code>fitContinuous</code></h2>
<p>First we will fit a Brownian motion (BM) model to log(body mass):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">BM &lt;-<span class="st"> </span><span class="kw">fitContinuous</span>(mytree, <span class="kw">log</span>(mydata[,<span class="st">&quot;BodySize_kg&quot;</span>]), <span class="dt">model =</span> <span class="kw">c</span>(<span class="st">&quot;BM&quot;</span>))</code></pre></div>
<p>To look at the output type:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">BM</code></pre></div>
<pre><code>## GEIGER-fitted comparative model of continuous data
##  fitted &#39;BM&#39; model parameters:
##  sigsq = 2.207510
##  z0 = 4.304110
## 
##  model summary:
##  log-likelihood = -98.541855
##  AIC = 201.083711
##  AICc = 201.583711
##  free parameters = 2
## 
## Convergence diagnostics:
##  optimization iterations = 100
##  failed iterations = 0
##  frequency of best fit = 1.00
## 
##  object summary:
##  &#39;lik&#39; -- likelihood function
##  &#39;bnd&#39; -- bounds for likelihood search
##  &#39;res&#39; -- optimization iteration summary
##  &#39;opt&#39; -- maximum likelihood parameter estimates</code></pre>
<p>The maximum likelihood estimates (<code>lnL</code>) of the model parameters are found near the top of the output. In a Brownian motion (BM) model we estimate the Brownian rate parameter, <span class="math inline">\(\sigma^2\)</span> or <code>sigsq</code> in the output above, which is <code>2.208</code> and the value of the trait at the root of the tree, <span class="math inline">\(X(0)\)</span> or <code>z0</code> in the output above, which is <code>4.304</code>. Other useful things in the output are the maximum-likelihood estimate (<code>lnL</code>) of the model (log-likelihood), the Akaike Information Criterion (<code>AIC</code>), sample-size corrected AIC (<code>AICc</code>) and the number of model parameters (free parameters) also known as <span class="math inline">\(k\)</span> in the literature. We will return to the AIC values below.</p>
<p>To fit an Ornstein-Uhlenbeck model to log(body mass) we only need to change the model in the formula we used above:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">OU &lt;-<span class="st"> </span><span class="kw">fitContinuous</span>(mytree, <span class="kw">log</span>(mydata[,<span class="st">&quot;BodySize_kg&quot;</span>]), <span class="dt">model =</span> <span class="kw">c</span>(<span class="st">&quot;OU&quot;</span>))</code></pre></div>
<p>To look at the output type:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">OU</code></pre></div>
<pre><code>## GEIGER-fitted comparative model of continuous data
##  fitted &#39;OU&#39; model parameters:
##  alpha = 2.718282
##  sigsq = 60.982371
##  z0 = 3.203383
## 
##  model summary:
##  log-likelihood = -70.843002
##  AIC = 147.686004
##  AICc = 148.729482
##  free parameters = 3
## 
## Convergence diagnostics:
##  optimization iterations = 100
##  failed iterations = 0
##  frequency of best fit = 0.05
## 
##  object summary:
##  &#39;lik&#39; -- likelihood function
##  &#39;bnd&#39; -- bounds for likelihood search
##  &#39;res&#39; -- optimization iteration summary
##  &#39;opt&#39; -- maximum likelihood parameter estimates</code></pre>
<p>As above, the maximum likelihood estimates (<code>lnL</code>) of the model parameters are found near the top of the output. In an Ornstein-Uhlenbeck (OU) model we estimate the Brownian rate parameter, <span class="math inline">\(\sigma^2\)</span> or <code>sigsq</code> in the output above, the value of the trait at the root of the tree, <span class="math inline">\(X(0)\)</span> or <code>z0</code> in the output above, and the selection strength parameter, <span class="math inline">\(\alpha\)</span> or <code>alpha</code> in the output above. As <code>alpha = 2.718</code> here, it suggests that there is evolution towards a body mass optimum.</p>
<p>Finally, to fit an Early Burst (EB) model to log(body mass):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">EB &lt;-<span class="st"> </span><span class="kw">fitContinuous</span>(mytree, <span class="kw">log</span>(mydata[,<span class="st">&quot;BodySize_kg&quot;</span>]), <span class="dt">model =</span> <span class="kw">c</span>(<span class="st">&quot;EB&quot;</span>))</code></pre></div>
<p>To look at the output type:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">EB</code></pre></div>
<pre><code>## GEIGER-fitted comparative model of continuous data
##  fitted &#39;EB&#39; model parameters:
##  a = -0.000001
##  sigsq = 2.208224
##  z0 = 4.304129
## 
##  model summary:
##  log-likelihood = -98.542390
##  AIC = 203.084780
##  AICc = 204.128258
##  free parameters = 3
## 
## Convergence diagnostics:
##  optimization iterations = 100
##  failed iterations = 0
##  frequency of best fit = 0.58
## 
##  object summary:
##  &#39;lik&#39; -- likelihood function
##  &#39;bnd&#39; -- bounds for likelihood search
##  &#39;res&#39; -- optimization iteration summary
##  &#39;opt&#39; -- maximum likelihood parameter estimates</code></pre>
<p>As above, the maximum likelihood estimates (<code>lnL</code>) of the model parameters are found near the top of the output. In an Early Burst (EB) model we estimate the Brownian rate parameter, <span class="math inline">\(\sigma^2\)</span> or <code>sigsq</code> in the output above, the value of the trait at the root of the tree, <span class="math inline">\(X(0)\)</span> or <code>z0</code> in the output above, and the rate of change parameter, <span class="math inline">\(a\)</span>. Here <code>a</code> is very close to 0 indicating that the rate of log(body mass) evolution in magical creatures has not decreased through time.</p>
<p>We can also extract the rate half-life, <span class="math inline">\(t_{\frac{1}{2}}\)</span>, for this model as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">log</span>(<span class="dv">2</span>)/<span class="kw">abs</span>(EB$opt$a)</code></pre></div>
<pre><code>## [1] 693147</code></pre>
<p>For these data, the rate half-life is almost 700,000 time units, much greater than the total time represented on the tree! This means over the course of magical creature evolution, body size rate has not halved (yet).</p>
<div id="comparing-models-of-evolution" class="section level3">
<h3><span class="header-section-number">6.3.1</span> Comparing models of evolution</h3>
<p>Often we want to know which of the models fits our variable best. We can use <code>fitContinuous</code> to fit the models we are interested in and can then compare them using AIC. We can extract the AICs from the models we fitted above as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">BM$opt$aic</code></pre></div>
<pre><code>## [1] 201.0837</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">OU$opt$aic</code></pre></div>
<pre><code>## [1] 147.686</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">EB$opt$aic</code></pre></div>
<pre><code>## [1] 203.0848</code></pre>
<p>The “best” model is the one with the smallest AIC, in this case the OU model. There is much debate about how big of a difference in AIC values can be classed as substantial improvement to a model fit (it usually ranges from 2-10 AIC units). Generally we use 4 units, so EB probably doesn’t fit substantially better than BM, but OU is substantially better than BM and EB.</p>
<p>Alternatively we can use <span class="math inline">\(\Delta\)</span>AIC or AIC weights to compare our models using the following code and the <code>geiger</code> function <code>aicw</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">aic.scores &lt;-<span class="st"> </span><span class="kw">setNames</span>(<span class="kw">c</span>(BM$opt$aic, OU$opt$aic, EB$opt$aic), <span class="kw">c</span>(<span class="st">&quot;BM&quot;</span>,<span class="st">&quot;OU&quot;</span>,<span class="st">&quot;EB&quot;</span>))
<span class="kw">aicw</span>(aic.scores)</code></pre></div>
<pre><code>##         fit    delta            w
## BM 201.0837 53.39771 2.540009e-12
## OU 147.6860  0.00000 1.000000e+00
## EB 203.0848 55.39878 9.339176e-13</code></pre>
<p><code>aicw</code> outputs the AIC (<code>fit</code>), <span class="math inline">\(\Delta\)</span>AIC (<code>delta</code>) and AIC weights (<code>w</code>) for each of the models we fitted. The best model is the model with <span class="math inline">\(\Delta\)</span>AIC = 0 or with AICw closest to 1. Using <span class="math inline">\(\Delta\)</span>AIC we can conclude that the OU model is the best fit to the data.</p>
</div>
<div id="problems-with-convergence-and-bounds" class="section level3">
<h3><span class="header-section-number">6.3.2</span> Problems with convergence and bounds</h3>
<p>Above we have mentioned the default bounds on each parameter. Sometimes these need to be changed because the model will not converge. This happens when the likelihood surface has long flat ridges that cause the likelihood search to get “stuck” (this is particularly common under the OU model). You can change bounds with the bounds argument in <code>fitContinuous</code>. Several bounds can be given at a time e.g. <code>bounds = list(sigsq = c(0, 0.1), alpha = c(0, 1))</code> would constrain both the <span class="math inline">\(\sigma^2\)</span> and <span class="math inline">\(\alpha\)</span> parameters.</p>
<p>For example, if an OU model keeps getting stuck you could try changing the lower bound on <span class="math inline">\(\alpha\)</span>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">OU &lt;-<span class="st"> </span><span class="kw">fitContinuous</span>(<span class="dt">phy =</span> mytree, <span class="dt">dat =</span> <span class="kw">log</span>(mydata[,<span class="st">&quot;BodySize_kg&quot;</span>]), <span class="dt">model =</span> <span class="kw">c</span>(<span class="st">&quot;OU&quot;</span>), 
                    <span class="dt">bounds =</span> <span class="kw">list</span>(<span class="dt">alpha =</span> <span class="kw">c</span>(<span class="fl">0.01</span>, <span class="dv">1</span>)))</code></pre></div>
<p>This example gives a warning message because <code>alpha</code> is over 1, so when we make the upper bound smaller the method ends up giving us this value instead because it’s as close to 1 as we are allowing the model to go.</p>
<hr />
</div>
</div>
<div id="references-2" class="section level2">
<h2><span class="header-section-number">6.4</span> References</h2>
<ul>
<li>Blomberg, S. P., T. Garland, and A. R. Ives. 2003. Testing for phylogenetic signal in comparative data: behavioral traits are more labile. Evolution 57:717–745.</li>
<li>Butler, M. A. and A. A. King. 2004. Phylogenetic comparative analysis: a modeling approach for adaptive evolution. The American Naturalist 164:683–695.</li>
<li>Cavalli-Sforza, L. L. and A. W. Edwards. 1967. Phylogenetic analysis. models and estimation procedures. American Journal of Human Genetics 19:233.</li>
<li>Cooper, N., R. P. Freckleton, and W. Jetz. 2011. Phylogenetic conservatism of environmental niches in mammals. Proceedings of the Royal Society B: Biological Sciences 278:2384–2391.</li>
<li>Cooper, N. and A. Purvis. 2010. Body size evolution in mammals: complexity in tempo and mode.The American Naturalist 175:727–738.</li>
<li>Cooper, N., Thomas, G.H., Venditti, C., Meade, A. &amp; Freckleton, R.P. (2016b) A cautionary note on the use of ornstein-uhlenbeck models in macroevolutionary studies. Biological Journal of the Linnaean Society</li>
<li>Felsenstein, J. 1973. Maximum likelihood and minimum-steps methods for estimating evolutionary trees from data on discrete characters. Systematic Biology 22:240–249.</li>
<li>Freckleton, R. P. and P. H. Harvey. 2006. Detecting non-brownian trait evolution in adaptive radiations. PLoS Biology 4:e373.</li>
<li>Hansen, T. F. 1997. Stabilizing selection and the comparative analysis of adaptation. Evolution Pages 1341–1351.</li>
<li>Harmon, L. J., J. B. Losos, T. Jonathan Davies, R. G. Gillespie, J. L. Gittleman, W. Bryan Jennings, K. H. Kozak, M. A. McPeek, F. Moreno-Roark, T. J. Near, et al. 2010. Early bursts of body size and shape evolution are rare in comparative data. Evolution 64:2385–2396.</li>
<li>Lande, R. 1976. Natural selection and random genetic drift in phenotypic evolution. Evolution 30:314–334.</li>
<li>Slater, G. J., L. J. Harmon, and M. E. Alfaro. 2012. Integrating fossils with molecular phylogenies improves inference of trait evolution. Evolution 66:3931–3944.</li>
<li>Slater, G. J. and M.W. Pennell. 2014. Robust regression and posterior predictive simulation increase power to detect early bursts of trait evolution. Systematic Biology 63:293–308.</li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="phylogenetic-generalised-least-squares-pgls-in-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="macroevolutionary-models-in-r-part-2-discrete-traits.html" class="navigation navigation-next " aria-label="Next page""><i class="fa fa-angle-right"></i></a>

<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/nhcooper123/TeachingMaterials/MSc_Museum/MacroModule/edit/master/05_MacroModelsinR_Cont.Rmd",
"text": "Edit"
},
"download": ["macro-module.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
