---
title: "References"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# What is macroecology?

## General
* Brown. 1995. Macroecology. University of Chicago Press. [book]
* Gaston & Blackburn. 2000. Pattern and process in macroecology. Blackwell Science. [book]
* MacArthur and Wilson.  1967. The theory of island biogeography. Princeton University Press.
* Rosenzweig.1995. Species diversity in space and time. Cambridge: Cambridge University Press. [book]
* Wilson.1992. The diversity of life. New York: Norton.  [book]
* Keith et al. 2012. What is macroecology. Biology Letters meeting report*

## History
* Wallace.1863. On the physical geography of the Malay Archipelago. Journal of the Royal Geographical Society London, 33: 217-234.
* Brown & Maurer. 1989. Macroecology: the division of food and space among species on continents. Science, 243: 1145-1150.

## Classic Macroecological Patterns
* Arrhenius. 1921. Species and area. Journal of Ecology, 9: 95-99.
* Willis.1922. Age and Area. Cambridge University Press.
* Brown and Nicoletto. 1991. Spatial scaling of the species composition - body masses of North-American land mammals. The American Naturalist, 138:1478-1512.
* Hutchinson and MacArthur. 1959. A theoretical ecological model of size distributions among species of animals. The American Naturalist, 93:117-125.
* Damuth. 1981.  Population density and body size in mammals. Nature, 290: 699-700.
* Brown. 1984. On the relationship between abundance and distribution of species. The American Naturalist, 124:255-279.
* Meiri & Dayan. 2003. On the validity of Bergmann’s rule. Journal of Biogeography, 30: 331-351. *

## Macroecological "rules"
* Bergmann. 1847. Ueber die verhältnisse der wärmeökonomie der thiere zu ihrer grösse. Gottinger studien. 3:595-708.
* McNab.1971. On the ecological significance of Bergmann's rule. Ecology, 52:845-854.
* Geist. 1987. Bergmann's rule is invalid. Canadian Journal of Zoology, 65:1035-1038.
* Ashton et al. 2000. Is Bergmann's rule valid for mammals? American Naturalist, 156:390-415.
* Blackburn et al. 1999. Geographic gradients in body size: a clarification of Bergmann's rule. Diversity and Distributions, 5:165-174.
* Allen. 1877. The influence of physical conditions in the genesis of species. Radical Review, 1:108–140.
* Rapoport. 1982. Areography: geographical strategies of species. Pergamon, New York. 
* Stevens. 1989. The latitudinal gradient in geographical range: how so many species coexist in the tropics. American Naturalist, 133:240-256.
* Gloger. 1833. Das Aba¨ndern der Vo¨gel durch Einfluss des Klimas. August Schulz, Breslau, Germany.

## Latitudinal diversity gradients and hotspots
* Grenyer et al. 2006. Global distribution and conservation of rare and threatened vertebrates. Nature, 444:93-96.
* Willig et al. 2003. Latitudinal gradients of biodiversity: pattern, process, scale, and synthesis.  Annual Reviews in Ecology Evolution and Systematics, 34: 273-309.
* Rohde. 1992. Latitudinal gradients in species diversity: the search for the primary cause. Oikos, 65: 514-527.
* Weir and Schluter. 2007. The latitudinal gradient in recent speciation and extinction rates of birds and mammals. Science, 315: 1574-1576.
* Jablonksi et al. 2006. Out of the tropics: evolutionary dynamics of the latitudinal diversity gradient. Science, 314: 102-106.
* Mittelbach et al. 2007. Evolution and the latitudinal diversity gradient: speciation, extinction and biogeography. Ecology Letters, 10: 315-331.*
* Schemske 2009. Is there a latitudinal gradient in the importance of biotic interactions? Annual Reviews in Ecology, Evolution and Systematics, 40: 245-269. *

## Biases
* Glaw et al. 2012. Rivaling the world's smallest reptiles: discovery of miniaturized and microendemic new species of leaf chameleons (Brookesia) from northern Madagascar. PLoS ONE, 7: e31314. 
* Isaac et al. 2004. Taxonomic inflation: its influence on macroecology and conservation. TREE, 19:464-469.

## Modern Macroecology
* Han et al. 2016. Global patterns of zoonotic disease in mammals. Trends in Parasitology, 32:565-577.  
* Stephens et al. 2016. The macroecology of infectious diseases: a new perspective on global-scale drivers of pathogen distributions and impacts. Ecology Letters, 19:1159-1171.*
* Newbold et al. 2016. Has land use pushed terrestrial biodiversity beyond the planetary boundary? A global assessment. Science, 353:288-291. 
* Newbold et al. 2015. Global effects of land use on local terrestrial biodiversity. Nature, 520:45–50.
* Harfoot et al. 2014. Emergent global patterns of ecosystem structure and function from a mechanistic general ecosystem model. PLoS Biology, 12:e1001841.

# What is macroevolution?

## General
Simpson 1944. Tempo and Mode in Evolution. [book]
Stanley. 1979. Macroevolution, Pattern and Process.  [book]

## Cited in the lecture
* Benson, R.B.J., et al. 2014. Rates of dinosaur body mass evolution indicate 170 million years of sustained ecological innovation on the Avian stem lineage. PLoS Biology, 12.
* Cooney,	C. et al 2017. Mega-evolutionary dynamics of the adaptive radiation of birds. Nature. online. doi:10.1038/nature21074.
* Erwin D.H. 2000. Macroevolution is more than repeated rounds of microevolution. Evol Dev. 2:78-84.
* Fritz, Susanne A., et al. 2013. Diversity in time and space: wanted dead and alive. Trends in Ecology & Evolution 28: 509-516.
* Givnish, T.J. et al. 2015. Orchid phylogenomics and multiple drivers of their extraordinary diversification. Proc. R. Soc. B 2015 282 20151553.
* Haldane, J.B.S. 1949. Suggestions as to quantitative measurement of rates of evolution. Evolution, 51-56.
* Jablonksi 2008. Species Selection: Theory and Data. Annual Reviews Ecology Evolution and Systematics. 39:501–24
* Jones, F.C. et al. 2012. The genomic basis of adaptive evolution in threespine sticklebacks. Nature 484, 55–61.
* Okasha, S. 2006. Evolution and the Levels of Selection. [book]
* Raup, D.M., & Sepkoski, J.J. 1982. Mass Extinctions in the Marine Fossil Record. Science, 215: 1501-1503.
