---
title: "Methods in Macroecology and Macroevolution"
author: "Natalie Cooper (natalie.cooper@nhm.ac.uk)"
date: "Feb 2017"
output:
  pdf_document: default
  html_document: default
---


# Module outline

### Module coordinator: Natalie Cooper
### natalie.cooper@nhm.ac.uk

## Module Aims
The aim of this module is to introduce you to some of the cutting-edge methods being used in macroecology and macroevolution, with particular focus on work being done right now at the Museum. 
Rather than concentrating on learning theory through lectures, the module will introduce you to various ways we collect, analyse and interpret macro-scale data with a large emphasis on practical work, mostly using R. 

## Datasets and practical handouts
All datasets and practical handouts are available on GitHub.
It can be tricky to download data from GitHub if you don't know what you're doing and/or don't want to clone the entire repository so the materials are also available at this DropBox link: [].
It will save time if you download this before coming to class.

## Timetable
There will be one morning and one afternoon session each day. 
Morning sessions will run from 10am-1pm, afternoon sessions from 2pm-5pm. 
Not every session will require a full three hours. 
Instructors for each session are below.

### Thursday 23rd February

**Morning:** What are macroecology and macroevolution? 
Introduction to the module, assessments, and aims.

**Afternoon:** Macroecology I: Macroecological patterns and diversity indices in R.

*Natalie Cooper (natalie.cooper@nhm.ac.uk)*

### Friday February 24th February

**Morning:** Big Data I: Using Big Data in conservation with the PREDICTS project.

*Andy Purvis (a.purvis@nhm.ac.uk)*

**Afternoon:** Big data II: Using the paleobiology database (PBDB) to get data on fossil species for macroecological and macroevolutionary analyses.

*Terri Cleary (t.cleary@nhm.ac.uk)*

### Monday February 27th February

**Morning:** Comparative Biology: The comparative method, dealing with phylogenetic non-independence in comparative analyses. 
PGLS in R.

**Afternoon:** Macroevolution I: Macroevolutionary patterns and models of evolution in R.

*Natalie Cooper (natalie.cooper@nhm.ac.uk)*

### Tuesday 28th February

**Morning:** Big data III: Using museum specimen data in macroecological and macroevolutionary analyses. 
Geometric morphometrics.

*Natalie Cooper (natalie.cooper@nhm.ac.uk)*

**Afternoon:** Macroecology II: case study using Foraminifera.

*Isabel Fenton (i.fenton@nhm.ac.uk)*

### Wednesday 1st March

**Morning:** Macroevolution II: Diversification.

**Afternoon:** Critical thinking: Do you trust your methods?

*Natalie Cooper (natalie.cooper@nhm.ac.uk)*

### Thursday 2nd March AND Friday 3rd March
**All day:** 
Practical: Using fossil assemblages to assess the impact of mass extinction events: comparative palaeoecology of Ordovician and Silurian fossil assemblages.

*Richard Twitchett (r.twitchett@nhm.ac.uk)*

## Assessment
There are two assessments connected to this module.

At the end of every practical there will be some practice questions. 
Save your answers and __R CODE__
The assessment will be an online MCQ test where the answers come from the practice questions or the code you used to answer them. 
I'll send a link on Tuesday 28th and you'll have a week to do this.
It shouldn't take more than 20 mins...
No write up will be required and the assessment will be completed by the end of the week, if not the end of the practical. 

The second assessment, although within this module, belongs to the Paleobiology module. 
Due to the large class size during that module it couldn't happen there so we've moved it here.
 However, the techniques and concepts are highly relevant to macroecology and macroevolution.
 Richard Twitchett (r.twitchett@nhm.ac.uk) will provide a full explanation of the assessment during the practical on Thursday 2nd March and Friday 3rd March. 
