---
title: "Practice Questions"
author: "Natalie Cooper (natalie.cooper@nhm.ac.uk)"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

# Practice Questions

## Diversity indices in R
1. Using `?diversity` find out how to calculate **inverse Simpson's index**, then calculate it for the Pokemon dataset. What is the inverse Simpson's index for site 10? 
2. Try out three other betadiversity indices with the pokemon data. Do they all agree? How would you interpret the results from the betadiversity analyses?
3. Create a new dataset of Pokemon sightings (or anything else you like).
Calculate species richness, Simpson's index, Jaccard's index, Chao2 estimate, and plot a species accumulation curve in colours of your choice.

## PGLS in R
1. What is $\lambda$ for primate social group size?
2. Make a plot of social group size against home range size. 
3. Does home range size differ significantly among the different primate genera?
4. What is Blomberg's K for adult body mass?
5. Run a PGLS analysis to determine the relationship between ln(longevity) (Y variable) and ln(body mass) (X variable). 
		1. How does this differ from the result obtained with an OLS regression? 
		1. Plot the result.
		1. Plot the lambda profile
		1. Look at the confidence intervals on the estimate of lambda. How would you interpret these?

## Macroevolutionary models
1. Fit Brownian, OU and Early burst models to the magical power variable.
Which model fits best according to AIC weights? How could you interpret this result biologically?
2. Fit equal rates, symmetric rates and all rates different models to the habitat variable.
Which model fits best according to AIC weights? How could you interpret this result biologically?
3. Reconstruct ancestral states for habitat on the phylogeny and plot the result (with node and tip labels) using colours of your choice.
4. Fit a multi-rate Brownian motion model using `OUwie`, with habitat types as regimes, and body size as the evolving trait. 
What would be your next step in trying to find the best fitting model for these variables?
How would you interpret the results?
5. Invent your own variable to add to the dataset and fit models of evolution (continuous or discrete) to it as appropriate.

## Geometric morphometrics
1. Plot the min/max for PC3 scores in comparison to the reference shape with three fold magnification.
2. In one plotting window, plot PC1 against PC2, PC2 against PC3, and PC1 against PC3 (clue `par(mfrow = ???)`). With the help of `pca.landmarks$rotation` and the whale photgraphs, can you interpret the plots in relation to the morphology of the species?
3. Perform a multivariate regression using PC1, PC2 and PC3 as response variables, and body size as the explanatory variable.
4. Perform a MANOVA using PC1, PC2 and PC3 as response variables, and diet as the explanatory variable.
5. Invent your own variable to add to the dataset and fit a regression or MANOVA to it as appropriate.
